### ISSUE TITLE
Icons fuer Schiffs-Systeme

### ISSUE THREAD

**Issue by usox** [usox/stu3-assets#1]
Derzeit fehlen uns noch Icons fuer die Schiffssysteme.
Folgende System gibt es:
- Energie (1)
- Impulsantrieb (2)
- Warpkern (3)
- Computer (4)
- Strahlenwaffe (5)
- Projektilwaffe/Torpedo (6)
- Tarnung (7)
- Langstreckensensoren (8)
- Nahbereichssensoren (9)
- Warpantrieb (10)
- Schilde (11)

Die Bilder werden im derzeit nicht vorhandenen `system`-Ordner erwartet und sollten sich von der Groesse her an den Warenicons orientieren

**Comment by Bielhelm** [comment]
?? Ask: Icons Schiffs-Syteme: 
24 x 22 sind alle Ress/Goods als (gif ) definiert, 
evtl. auch in png selbe Grösse Echtfarben ok?
einfach neuen Ordner "system" im "gfx" anlegen ?

**Comment by usox** [comment]
Png wäre ok - für die GUI ist das nicht tragisch. Die Größe kannst du auch gern als Richtwert sehen. In der gleichen Zeile in der GUI sind eben schon solche Waren-Bilder drin, weshalb es von der Größe her passen würde
