### ISSUE TITLE
Icons für Systeme falsch betitelt

### ISSUE THREAD

**Issue by Huxinator** [usox/stu3-assets#21]
Die Miniicons für Systeme wie bspw. in der Kolonieansicht zu sehen, haben scheinbar im Grafiknamen falsche IDs.

**Comment by Bielhelm** [comment]
Teilweise haben die Fields und Buildings nicht nur falsche Nummern, sondern es bestehen auch Bilder die einen Ordner haben, aber im SQL Dump nicht betitelt sind oder mehrmals mit dem selben Namen auftauchen. Da sollte man sich was einfallen lassen. Bis dahin müssen wir halt improvisieren.

**Comment by usox** [comment]
Hier gehts um Systemicons und das Problem ich wohl erledigt, oder @Huxinator ?

**Comment by Huxinator** [comment]
Richtig. Ist erledigt.
