### ISSUE TITLE
Dist Dokumentation

### ISSUE THREAD

**Issue by Bielhelm** [usox/stu3-assets#81]
Die bisherige Dokumentation für Bilder wurde jetzt mehrfach erprobt und immer wieder geändert. Im Ordner stu3-assets/dist/ sind daher inzwischen zu finden : 

* im Ordner /arbeitslisten/
für die Arbeit relavante Listen in Excel, oo oder txt Format
* im Ordner /github/
Anleitungen zum täglichen Gebrauch für Github Neulinge
* im Ordner /Vorlagen/
alle vorhandenen Vorlagen, die für die Erstellung von Einzelbilder Pate gestanden haben und jeweils eine Quellenliste, in der alle möglichen Dateien enthalten sind, welche verwendet wurden oder auch nur diejenigen, welche in die engere Wahl genommen wurden.

Zum Ordner /vorlagen/ und zur sinnvollen Verwendung ist jetzt aktuell folgende Frage aufgetaucht:

Inwieweit sollen die Originalbilder aus Internet oder Matritzen größentechnisch miteinbezogen werden? 
Bei einigen Bildern wird 50 MB überschritten und ne Mahnung ausgeworfen. 

Wie groß setzen wir die max. Größe von Vorlagen im Vergleich zu den verwendeten Vignetten (40x40 bei Fields und 100x100 bei research) fest? (1 : x) 

Aus aktuellen Anlass: Die Doku in /dist/ ist wegen sehr großer Matritzen und Org.bilder aus paint.net (fields, research) am überlaufen, während selbstgebastelte Bilder bei Photoshop (buildings) grade 300 Kb groß sind beim 10x fachen der verwendeten Bilder ingame.

**Comment by usox** [comment]
Meine Aussage zu dem Thema war:
Es sollten Quellen dokumentiert werden bzw. Arbeitsmaterial zur Verfuegung gestellt werden, damit auch Dritte mit gleichem bzw. aehnlichem Material arbeiten kann. Die entscheidung, wie das auszusehen hat, ueberlasse ich euch

**Comment by Bielhelm** [comment]
Demnach werde ich das vorhandene Vorlagenmaterial vereinfachen und zugeschnitten auf 1:10 begrenzen. (bei z. B 100x100 dann auf 1000x1000 max. Vorlagengröße) Das sollte reichen.
